### ISSUE TITLE
Fail to replicate CustomReducerAction example

### ISSUE THREAD

**Issue by Gilstroem** [j0nas/light-form#14]
Using exact same code, apart from importing Reducer from light-form, I can not replicate the example. Action is fired fine (when inspected in redux-dev-tools), but has no effect on state.

As I said, the only thing that is different is from where the Reducer is imported, so my best guess is that it has to do with that

**Comment by j0nas** [comment]
Yes, light-form exports its own reducer which you're meant to use in conjunction with the fields.

**Comment by Gilstroem** [comment]
Yes - That is what I am doing; what I meant is that the only difference between my code (when failing) and your example is that it imports 'Reducer' from light-form instead of locally. It shouldn't make a difference, but that is the only thing I can see that is different.

I've posted screenshots of the code - form works as normal/expected, and 'RESET_FORM' event fires - but form does not clear

<img width="660" alt="screen shot 2017-07-07 at 12 10 34" src="https://user-images.githubusercontent.com/16057281/27955568-552ea44c-630d-11e7-97d2-cce77fccd7d9.png">
<img width="698" alt="screen shot 2017-07-07 at 12 09 42" src="https://user-images.githubusercontent.com/16057281/27955569-554fbf38-630d-11e7-8b33-9b7d1a5f6472.png">

**Comment by j0nas** [comment]
Sorry I haven't replied earlier. Is it some naming issue? (In regards to the form being named 'newRoomForm') Is there any way you could provide me access to the entire codebase, so I be able to look at the issue on my machine?

**Comment by Gilstroem** [comment]
No problem at all,

I've invited you to the repo now - I've checked for naming problems, but can't seem to find anything obvious. Everything works perfectly fine (values are being updated), but the state does not clear when RESET_FORM action is dispatched

**Comment by j0nas** [comment]
If I go to actions.js and add `dispatch(send.RESET_FORM())` as the first thing the function does, the form gets cleared at my end when I submit the modal. I can't verify complete functionality as I don't have the backend required. But if you still are having trouble getting it to work, it must be something that happens with the lines above send.RESET_FORM() as it works fine when called otherwise.

Also, don't check in node_modules, add a .gitignore file and list node_modules there. If you're planning to use the repository for a while, I'd delete it and make a new one if I were you, as the many files in node_modules that initially were checked in now will stay a part of that repository's history.

**Comment by Gilstroem** [comment]
Thanks a lot @j0nas for helping out! - you are correct, in that it works when on top, which is how I'll do it for now. I suspect that it somehow failed because the component was unmounted by the time it was called, perhaps. 

Thanks for the advice on the repo, I'll keep that in mind; I just uploaded that quickly for you to troubleshoot - I'm using other means of version control for this project atm. 

I'll be closing this issue, thanks again

**Comment by j0nas** [comment]
No problem, sorry it took me some time. As always, let me know if any more issues arise. 😄
